fix

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -10,85 +10,85 @@ jobs:
   test:
     runs-on: ubuntu-22.04
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-    - name: Lint markdown data
-      run: yarn --cwd=ci && node ci/tests-fiches.mjs
+      - name: Lint markdown data
+        run: yarn --cwd=ci && node ci/tests-fiches.mjs
 
-    - name: Set up Ruby
-      uses: ruby/setup-ruby@v1
-      with:
-        ruby-version: 3.4.1
-        bundler-cache: true
+      - name: Set up Ruby
+        uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: 3.4.1
+          bundler-cache: true
 
-    - name: Lint Ruby with Rubocop
-      run: bundle exec rubocop
+      - name: Lint Ruby with Rubocop
+        run: bundle exec rubocop
 
-    - name: Install npm dependencies
-      uses: actions/setup-node@v4
-      with:
-        node-version: 20
-        cache: 'npm'
-    - run: npm ci
+      - name: Install npm dependencies
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: "npm"
+      - run: npm ci
 
-    - name: Check Javascript/JSON linting
-      run: npm run lint
+      - name: Check Javascript/JSON linting
+        run: npm run lint
 
-    - name: Unit tests
-      run: bundle exec rspec
+      - name: Unit tests
+        run: bundle exec rspec
 
-    #- name: Check data structure
-    #  run: make validate
+      #- name: Check data structure
+      #  run: make validate
 
-    - name: Unit tests
-      run: bundle exec rspec
+      - name: Unit tests
+        run: bundle exec rspec
 
-    - name: "Check authors file name structure (first_name.last_name.md)"
-      run: |
-        if ls content/_authors | grep --line-regexp --invert-match '[a-z_.-]\+\.[a-z_.-]\+\.md'
-        then cat <<EOF
-          One or more authors do not have the expected structure.
-          Contact a website administrator if your generated author file breaks the validator.
-          Notes:
-          A dot (.) can only appear as a separator between the first and the last names.
-          Dashes in names are kept as-is.
-          Spaces are replaced by underscores (_).
-          File extension must be '.md'
-        EOF
-          exit 1
-        fi
+      - name: "Check authors file name structure (first_name.last_name.md)"
+        run: |
+          if ls content/_authors | grep --line-regexp --invert-match '[a-z_.-]\+\.[a-z_.-]\+\.md'
+          then cat <<EOF
+            One or more authors do not have the expected structure.
+            Contact a website administrator if your generated author file breaks the validator.
+            Notes:
+            A dot (.) can only appear as a separator between the first and the last names.
+            Dashes in names are kept as-is.
+            Spaces are replaced by underscores (_).
+            File extension must be '.md'
+          EOF
+            exit 1
+          fi
 
-    - name: Check Jekyll configuration
-      run: bundle exec jekyll doctor
+      - name: Check Jekyll configuration
+        run: bundle exec jekyll doctor
 
-    - name: Jekyll build
-      run: bundle exec jekyll build --trace
+      - name: Jekyll build
+        run: bundle exec jekyll build --trace
 
-    - name: Check HTML common mistakes
-      run: make html-proofer
+      - name: Check HTML common mistakes
+        run: make html-proofer
 
-    - name: HTML5 Validator
-      uses: Cyb3r-Jak3/html5validator-action@master
-      with:
-        root: _site
-        skip_git_check: true
+      - name: HTML5 Validator
+        uses: Cyb3r-Jak3/html5validator-action@master
+        with:
+          root: _site
+          skip_git_check: true
 
-    - name: Lint JSON API pages
-      run: bundle exec jsonlint _site/api/v*/*.json
+      - name: Lint JSON API pages
+        run: bundle exec jsonlint _site/api/v*/*.json
 
-    - name: "Upload Artifact"
-      uses: actions/upload-artifact@v4
-      with:
-        name: _site
-        path: _site
-        retention-days: 1
+      - name: "Upload Artifact"
+        uses: actions/upload-artifact@v4
+        with:
+          name: _site
+          path: _site
+          retention-days: 1
 
-    - name: Wait for server to start
-      run: |
-        (bundle exec jekyll serve --no-watch --skip-initial-build)&
-        while ! curl --silent http://localhost:4000
-        do sleep 1
-        done
+      - name: Wait for server to start
+        run: |
+          (bundle exec jekyll serve --no-watch --skip-initial-build)&
+          while ! curl --silent http://localhost:4000
+          do sleep 1
+          done
 
   axe:
     needs: [test]
@@ -133,9 +133,20 @@ jobs:
             killall -9 http-server
         env:
           URL: "http://127.0.0.1:8080"
-
+      - name: Test output
+        run: |
+          echo "${{ steps.axe.outputs.stdout }}" > ./out.txt
+          echo "${{ steps.axe.outputs.stderr }}" >> ./out.txt
+          AXE_DETAILS=$(cat ./out.txt | sed "s/Testing\ http:.* 0 violations found\!/x/")
+          echo "AXE_DETAILS:"
+          echo $AXE_DETAILS
+          AXE_ERROR=$(echo "$AXE_DETAILS" | grep "violations found") || 0
+          echo "AXE_ERROR:"
+          echo $AXE_ERROR
+          echo "AXE_DETAILS=$AXE_DETAILS" >> "$GITHUB_ENV"
+          echo "AXE_ERROR=$AXE_ERROR" >> "$GITHUB_ENV"
       - name: Comment pull request
-        if: always()
+        if: ${{ env.AXE_ERROR }}
         uses: marocchino/sticky-pull-request-comment@v2
         with:
           header: axe-core-comment
@@ -144,7 +155,10 @@ jobs:
             ## ♿️ Axe report
             Audited website : ${{ env.WEBSITE_TO_AUDIT }}
             ```
-            ${{ steps.axe.outputs.stdout }}
-            ${{ steps.axe.outputs.stderr }}
+            ${{ env.AXE_DETAILS }}
             ```
             *This report has been generated using [@axe-core/cli](https://github.com/dequelabs/axe-core-npm/blob/develop/packages/cli).*
+      - name: Exit pull request
+        if: ${{ env.AXE_ERROR }}
+        run: |
+          exit 1
